### ISSUE TITLE
EL6 distros using runit instead of upstart

### ISSUE THREAD

**Issue by andy-dufour** [chef-cookbooks/push-jobs#106]
### Cookbook version
3.2.2

### Chef-client version
12.14

### Platform Details
RHEL & CentOS6

### Scenario:
Use upstart as init provider.

### Steps to Reproduce:
Install push jobs on CentOS or RHEL 6. 

### Expected Result:

The default init provider on EL6 distros is upstart, we should use it.

### Actual Result:
Runit will be installed, instead of using an upstart based service.

**Comment by andy-dufour** [comment]
Have a rudimentary fix available: https://github.com/andy-dufour/push-jobs/tree/ad/el6_upstart

Default service provider on CentOS 6 resolves to sysvinit (Or chef::provider::service::redhat, which defaults to sysvinit), so I've had to explicitly set the provider to Upstart. Not great.

Open to other ideas. Going to rethink other options and look at adding some tests.

**Comment by iennae** [comment]
All platforms other than Windows are using runit for service management. We're looking at how to improve this.

**Comment by iennae** [comment]
Please take a look at version 5.0.0 of this cookbook. Upstart added its own complexities so there is a new sysvinit resource. The init script needs some polishing but let me know how this works for you.

**Comment by tas50** [comment]
5.2.0 now uses Upstart on RHEL 6
