### ISSUE TITLE
sysv style init script does not background the daemon 

### ISSUE THREAD

**Issue by lizzabeth** [chef-cookbooks/push-jobs#123]
### Cookbook version
5.0.0

### Chef-client version

12.19.36

### Platform Details

centos 6.6

### Scenario:

The new sysv initscript does not background the client and hence any `service[chef-push-jobs-client]` starts or restarts hang indefinitely.

### Steps to Reproduce:

Run this cookbook on any sysvinit distro. 

### Expected Result:

The service will start and the converge will continue.

### Actual Result:

The converge runs until timeout (if configured) on any start or restart of the chef-push-jobs-client daemon since it does not background.

**Comment by cheeseplus** [comment]
Fixed by #123
