### ISSUE TITLE
chef-client run giving ssl error while push jobs client installation

### ISSUE THREAD

**Issue by erarunkumar** [chef-cookbooks/push-jobs#126]
### Cookbook version
[5.1.1]

### Chef-client version
[13.1.31]

### Platform Details
[centos6]

### Scenario:
[I am running chef-client from node install the push job client but getting SSL error as logs below:
Uploaded the push jobs and dependent cookbooks on chef server and Add the cookbook in runlist of node. Trying the command chef-client but not working. I know why this issue is coming.
This is coming because i am on my organization network where a certificate based auth mechanism on firewall, can anybody guide me either a way to skip that certificate or where to add that certificate on node/chef server/workstation etc.]

### Steps to Reproduce:
[I don't think without such env we can replicate in local]

### Expected Result:
[want the pushjobs client installed]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible
[chef-client.txt](https://github.com/chef-cookbooks/push-jobs/files/1080805/chef-client.txt)

.]

**Comment by cheeseplus** [comment]
Does this issue still exist? That looks like it was either an errant outage or you're node is subject to some sort of intercepting proxy.

**Comment by iennae** [comment]
If you are still experiencing this problem please reopen with additional details.
