### ISSUE TITLE
Service fails on Amazon Linux with Chef 13.x

### ISSUE THREAD

**Issue by zts** [chef-cookbooks/push-jobs#128]
### Cookbook version
5.1.1

### Chef-client version
13.2.20

### Platform Details
Amazon Linux 2017.03

### Scenario:
Install push-jobs and start the push-jobs service on Amazon Linux using Chef 13.x.

### Steps to Reproduce:
Add `recipe[push-jobs]` to the run list of an Amazon LInux node using Chef 13.

### Expected Result:
push-jobs successfully installed, and service started.

### Actual Result:
Chef run fails:
```
RuntimeError
------------
This cookbook currently supports only Windows, Debian-family Linux, and RHEL-family Linux.

Cookbook Trace:
---------------
  /opt/kitchen/cache/cookbooks/push-jobs/recipes/default.rb:31:in `from_file'
  /opt/kitchen/cache/cookbooks/test/recipes/default.rb:15:in `from_file'
```

I believe this cookbook happened to work on Amazon Linux with Chef 12.x, but the reclassification of that distribution into `platform_family == 'amazon'` put a stop to that.

I'll submit a PR to resolve this issue.

**Comment by iennae** [comment]
Take a look at PR #127 as it looks like progress is being made there. PRs happily accepted. Thanks for reporting this issue!
