### ISSUE TITLE
System V init template should not use basename $0 to name the PID file

### ISSUE THREAD

**Issue by chris-carr-bose** [chef-cookbooks/push-jobs#143]
### Cookbook version
5.1.2

### Chef-client version
12.17.44

### Platform Details
Amazon Linux AMI release 2015.03 running on EC2

### Scenario:
Restart push jobs using /sbin/service utility.

### Steps to Reproduce:
1. Run this cookbook on a platform with SysV init scripts. Run the cookbook in such a way as to start and enable the push-jobs service.
2. Reboot the system.
3. Wait for system to finish booting.
4. Execute "ls /var/run". Note the presence of the file S50chef-push-jobs-client.pid which was written during system start. Note also no other files related to push jobs.
5. Execute "cat /var/run/S50chef-push-jobs-client.pid". Note the content.
6. Execute "ps aux | grep push-jobs". Note two processes, one of which with PID matching the content of S50chef-push-jobs-client.pid, the other a child of the one.
7. Execute "sudo service chef-push-jobs-client stop". Note that the service utility reports that push jobs is "Not running".
8. Execute "sudo service chef-push-jobs-client start.
9. Execute "ps aux | grep push-jobs". Note that there are now four processes.
10. Execute "ls /var/run". Note that S50chef-push-jobs-client.pid and chef-push-jobs-client.pid are both present.
11. Cat the two files. Note that both PIDs are running processes.

### Expected Result:
In step 4, the file should be named "chef-push-jobs-client.pid".
In step 9, there should be two processes: a parent and a child.
In step 10, there should be only one PID file, and it should be named "chef-push-jobs-client.pid".

### Actual Result:
In step 4, the file is named "S50chef-push-jobs-client.pid"
In step 9, there are four processes: two parents, and two children.
In step 10, there are two PID files, named "chef-push-jobs-client.pid" and "S50chef-push-jobs-client.pid".

**Comment by tas50** [comment]
@chris-carr-bose Can you open up a PR to fix this?

**Comment by tas50** [comment]
The initial fix here is in 5.3.0. Thanks for the PR
