### ISSUE TITLE
Add support for other init systems beyond runit and Windows

### ISSUE THREAD

**Issue by charlesjohnson** [chef-cookbooks/push-jobs#34]
Please add support for other init systems on supported platforms, such as sysvinit and systemd units.

**Comment by jtimberman** [comment]
We should do for this cookbook what I propose for the chef client cookbook here

https://github.com/opscode-cookbooks/chef-client/issues/282

See the services section.

**Comment by charlesjohnson** [comment]
:+1: to @jtimberman's idea.

**Comment by thenoid** [comment]
:+1: to this

**Comment by yvovandoorn** [comment]
👍

**Comment by tas50** [comment]
We're planning to implement basically what @jtimberman referenced above with chef-client.  We'd replicate that same functionality with the push jobs provider.  Out of the box the provider would just use whatever the native init system was.  You could override that if you enjoyed runit for some reason, but out of the box you'd get sys-v, systemd, or upstart depending on platform and release.

**Comment by yvovandoorn** [comment]
That sounds delightful @tas50! Working with a team trying to implement this behind the firewall and the runit dependencies are a bit.... annoying. Seeing the cookbook move to this is ❤️.

**Comment by tas50** [comment]
This was done
