### ISSUE TITLE
push-Job on windows harcoded config on service and config file is ignored

### ISSUE THREAD

**Issue by Roviluca** [chef-cookbooks/push-jobs#39]
Hello,

we are checking this cookbook on windows and we are experiencing some issues due to harcoded values.
1) #38  this is bad on linux, on windows is even worst...
2) the configuration file that i mentioned in point one is ignored completely by pushy service
3) because of point 2 is impossible to define a whitelist (only chef-client can be pushed to the client)

thanks

**Comment by cheeseplus** [comment]
Fixed by #42
