### ISSUE TITLE
No package available on Ubuntu 14.04 EC2 instance

### ISSUE THREAD

**Issue by pghalliday** [chef-cookbooks/push-jobs#45]
I get the following error:

```
apt_package[push-client] (/var/chef/cache/cookbooks/chef-ingredient/libraries/helpers.rb line 46) had an error: Chef::Exceptions::Package: No candidate version available for opscode-push-jobs-client
```

tried doing an `apt-get update` first, but still no luck

**Comment by cwebberOps** [comment]
@pghalliday We are working on fixing this but in the meantime you can set `node.default['apt-chef']['codename'] = 'precise'` and get it to install.

**Comment by cwebberOps** [comment]
@manderson26 can you please update this issue when the next version of the 1.x branch of push jobs is promoted?

**Comment by pghalliday** [comment]
Thanks

**Comment by mmzyk** [comment]
I'm not sure what version of the push jobs client this affected, but this should no longer be an issue with the 2.1.0 release at the very least.
