### ISSUE TITLE
How to override default server name provided by Pushy server to the client?

### ISSUE THREAD

**Issue by klutarevich** [chef-cookbooks/push-jobs#47]
I set up Pushy server on my Chef 12 server and installed Pushy client on one of the Windows machines (all working in AWS). When started Pushy client successfully connects to Chef server via HTTPS but then tries to connect to the same server (via TCP) using a completely different FQDN (see the second the third log records below). I want to make Pushy client connect to the server using the same FQDN i.e. tcp://chef.myorg.com:10002 and tcp://chef.myorg.com:10000.

> [2015-09-17T18:01:03+00:00] INFO: [i-77a2f5dc] Retrieving configuration from https://chef.myorg.com/organizations/myorg/pushy/config/i-77a2f5dc ...
> [2015-09-17T18:01:03+00:00] INFO: [i-77a2f5dc] Connecting to command channel at tcp://ip-10-5-5-41.ec2.internal:10002
> [2015-09-17T18:01:03+00:00] INFO: [i-77a2f5dc] Listening for server heartbeat at tcp://ip-10-5-5-41.ec2.internal:10000

**Comment by cheeseplus** [comment]
You can override this with `zeromq_listen_address` and can find information https://docs.chef.io/config_rb_push_jobs_server.html
