### ISSUE TITLE
ERROR: undefined method `compile_time' for Chef::Resource::ChefGem

### ISSUE THREAD

**Issue by dmdu** [chef-cookbooks/push-jobs#48]
I am having issues with running the push-jobs [2.4.2] cookbook on my Ubuntu 14.04. 

attributes/default.rb unchanged, still contains:

default['push_jobs']['package_url']                 = nil
default['push_jobs']['package_checksum']            = ''"

Tried going to previous versions of the push-jobs cookbooks, but no success there. Looked for similar issues on the web, but couldn't find anything useful. Don't know what to try next.

Output of the chef-client run (on a node with: "Run List:    recipe[push-jobs]"):

root@head:/chef-repo/cookbooks# chef-client 
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: ["push-jobs"]
Synchronizing Cookbooks:
  - runit
  - packagecloud
  - push-jobs
  - windows
  - chef_handler
  - chef-ingredient
  - apt-chef
  - apt
  - yum-chef
  - yum
Compiling Cookbooks...
Converging 9 resources
Recipe: push-jobs::linux
  * chef_ingredient[push-client] action install
    
    ================================================================================
    Error executing action `install` on resource 'chef_ingredient[push-client]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `compile_time' for Chef::Resource::ChefGem
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef-ingredient/libraries/helpers.rb:61:in `block in install_mixlib_versioning'
    /var/chef/cache/cookbooks/chef-ingredient/libraries/helpers.rb:59:in `install_mixlib_versioning'
    /var/chef/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:38:in `block in <class:ChefIngredient>'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/push-jobs/recipes/linux.rb
    
     41: chef_ingredient 'push-client' do
     42:   version node['push_jobs']['package_version']
     43:   package_source "#{Chef::Config[:file_cache_path]}/#{package_file}" if package_url
     44: end
     45: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/push-jobs/recipes/linux.rb:41:in `from_file'
    
    chef_ingredient("push-client") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_ingredient
      cookbook_name "push-jobs"
      recipe_name "linux"
      version :latest
      product_name "push-client"
    end
    

Running handlers:
[2015-09-18T19:16:43-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-18T19:16:43-05:00] ERROR: Exception handlers complete
[2015-09-18T19:16:43-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.998163944 seconds
[2015-09-18T19:16:43-05:00] ERROR: chef_ingredient[push-client] (push-jobs::linux line 41) had an error: NoMethodError: undefined method `compile_time' for Chef::Resource::ChefGem
[2015-09-18T19:16:43-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jtimberman** [comment]
You need to upgrade chef to version 12.1.0 or higher. I recommend 12.4.1

**Comment by dmdu** [comment]
Upgrading now. Thanks!
