### ISSUE TITLE
json_path not path and File.read

### ISSUE THREAD

**Issue by thenoid** [chef-cookbooks/push-jobs#61]
https://github.com/chef-cookbooks/push-jobs/blob/master/libraries/helpers.rb#L87

'path' is a directory, 'json_path' is the json file

**Comment by thenoid** [comment]
So this and #57 are related

the full bugfix should be:

 ```
JSON.parse(File.read(json_path))['build_version']
```

JSON.parse doesn't appear to implement file reading.

**Comment by manderson26** [comment]
This should be fixed by PR #63

**Comment by thenoid** [comment]
thx! :+1:
