### ISSUE TITLE
Latest Chef-ingredients dependency requires Chef 12.5.0

### ISSUE THREAD

**Issue by normalfaults** [chef-cookbooks/push-jobs#66]
Where as push jobs lists Chef 11.4 + 

Chef ingredients cookbook produces error on chef < 12.5.0

**Comment by jtimberman** [comment]
You can either use `chef-ingredient` v0.14.0, or upgrade your chef client package on your systems. To use the older version of `chef-ingredient` will depend on your cookbook workflow - if you're using berkshelf, librarian, or manually managing the cookbook versions.
