### ISSUE TITLE
Incorrect information for push-jobs

### ISSUE THREAD

**Issue by ThePhunny** [chef-cookbooks/push-jobs#67]
chef-ingredients is required by push-jobs.
chef-ingredients requires Chef 12.+ 
push-jobs can not run on Chef 11.4+

**Comment by mmzyk** [comment]
I'm confused by what you've written here @ThePhunny. Push Jobs works fine with the Chef Server 11.4 and greater, so I'm not sure what behavior you were seeing. I'm going to close this, but please reopen if you have more info to share. Sorry for the slow reply on this.
