### ISSUE TITLE
After upgrading to 3.2, logs no longer show up at /var/log/push-jobs-client/current

### ISSUE THREAD

**Issue by gliptak** [chef-cookbooks/push-jobs#94]
### Cookbook version
```3.2```

### Chef-client version
```Chef: 12.10.24```

### Platform Details
Oracle Linux Server release 7.1

### Scenario:
After upgrading to ```3.2```, logs no longer show up at ```/var/log/push-jobs-client/current```. 

### Expected Result:
Log file available.

### Actual Result:
No log file.

**Comment by gliptak** [comment]
Based on https://github.com/chef-cookbooks/push-jobs/pull/87, now the service is configured using ```systemd```

**Comment by tas50** [comment]
Your logs are now going to use journald as the service is running via the native systemd init provider

**Comment by gliptak** [comment]
@tas50 Thank you for the pointer. The ```journald`` logs do not contain output from the command ran (like ```chef-client```), which was the default behaviour in the previous versions. Thanks

**Comment by gliptak** [comment]
The workaround we found is to redirect the ```chef-client``` logs into a separate file. Modify ```/etc/chef/client.rb```:

    #Add below line to change log level and location 
    log_level                     :info
    log_location    "/var/log/chef.log"
