### ISSUE TITLE
Problems installing from cookbook on CentOS 7

### ISSUE THREAD

**Issue by izghitu** [chef-cookbooks/push-jobs#95]
### Cookbook version

3.2.0
### Chef-client version

Chef: 12.12.15
### Platform Details

CentOS 7.2.1511
### Scenario:

Trying to install push-jobs client using cookbook
### Steps to Reproduce:

chef-client -l debug -o recipe[push-jobs]
### Expected Result:

It should install the push-jobs client latest version
### Actual Result:

Starting Chef Client, version 12.12.15
[2016-08-06T02:59:18-07:00] WARN: Run List override has been provided.
[2016-08-06T02:59:18-07:00] WARN: Original Run List: [recipe[XXX]]
[2016-08-06T02:59:18-07:00] WARN: Overridden Run List: [recipe[push-jobs]]
resolving cookbooks for run list: ["push-jobs"]
Synchronizing Cookbooks:
- push-jobs (3.2.0)
- runit (1.7.8)
- packagecloud (0.2.4)
- windows (1.44.1)
- chef_handler (1.4.0)
- chef-ingredient (0.19.0)
- compat_resource (12.10.6)
  Installing Cookbook Gems:
  Compiling Cookbooks...
  Converging 4 resources
  Recipe: push-jobs::package
- chef_ingredient[push-jobs-client] action install
  Recipe: <Dynamically Defined Resource>

```
* chef_gem[mixlib-install] action install (up to date)

================================================================================
Error executing action `install` on resource 'chef_ingredient[push-jobs-client]'
================================================================================

RuntimeError
------------
No package found for 'push-jobs-client' with version 'latest' for current platform in 'stable' channel.
Check that the package exists.

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:95:in `configure_from_channel'
/var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:46:in `configure_package'
/var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
/var/chef/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/push-jobs/recipes/package.rb

 44: chef_ingredient 'push-jobs-client' do
 45:   version package_version || node['push_jobs']['package_version']
 46:   package_source "#{Chef::Config[:file_cache_path]}/#{package_file}" if package_url
 47:   platform_version_compatibility_mode true
 48: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/push-jobs/recipes/package.rb:44:in `from_file'

chef_ingredient("push-jobs-client") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :chef_ingredient
  cookbook_name "push-jobs"
  recipe_name "package"
  platform_version_compatibility_mode true
  product_name "push-jobs-client"
end

Platform:
---------
x86_64-linux
```

Running handlers:
[2016-08-06T02:59:19-07:00] ERROR: Running exception handlers
Running handlers complete
[2016-08-06T02:59:19-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2016-08-06T02:59:19-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-08-06T02:59:19-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-06T02:59:19-07:00] ERROR: chef_ingredient[push-jobs-client](push-jobs::package line 44) had an error: RuntimeError: No package found for 'push-jobs-client' with version 'latest' for current platform in 'stable' channel.
Check that the package exists.

[2016-08-06T02:59:19-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The strange thing is that I have another server running virtually the same OS and settings and the install goes fine on that one. The only difference between the 2 servers is the kernel they are running. The ones that is working runs the standard CentOS kernel. This one that does not work runs this kernel:
Linux HOSTNAME 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux

Please let me know how do I fix this issue.
Thanks in advance

**Comment by izghitu** [comment]
Same issue encountered on a CloudLinux 7 server running at the same data center in a different location but with the same kernel. This indicates that somehow the custom kernel is the culprit here.

Any help please?

**Comment by iennae** [comment]
This looks like either an issue with mixlib-install gem or the chef-ingredient cookbook. We will have to do more digging to check this out. If you change "latest" to "2.2.0" and give us the results there that would be helpful in us identifying where the problem is. Thanks!

**Comment by izghitu** [comment]
@iennae you can close this, I am no longer able to reproduce it and it was a long time ago. Thanks for the response though.

**Comment by iennae** [comment]
Thanks for the update!
