### ISSUE TITLE
Push Jobs 3.2.1 is failing on Windows 2012R2 with "No info for version ''"

### ISSUE THREAD

**Issue by ceseuron** [chef-cookbooks/push-jobs#98]
### Cookbook version

3.2.1
### Chef-client version

12.13.37
### Platform Details

Windows Server 2012 R2 running on VMware VSphere 5.5
### Scenario:

If push-jobs cookbook is included in the Chef Client run, the run will fail with the following error:

`No info for version ''`

I have examined the stack trace and it appears to be this block of code in ./libraries/helpers.rb lines 42 through 57: https://github.com/chef-cookbooks/push-jobs/blob/master/libraries/helpers.rb

Specifically, the **self.family_by_version(version)..end** function appears to be getting a null value for the **version** variable.
### Steps to Reproduce:

I am not using this cookbook in any capacity beyond a standard inclusion in a node runlist. I am not depending on this cookbook in any others, nor am I including any special resources. To reproduce this:
1. Deploy push-jobs 3.2.1 to your Chef server.
2. Assign push-jobs 3.2.1 to a Windows Server 2012 R2 node that is already attached to your server.   Your Windows installation should not already have the Push Jobs client installed.
3. Run chef-client from a command line.
### Expected Result:

I expect push-jobs cookbook to download, install, and configure push jobs.
### Actual Result:

The entire chef run fails when it tries to run push-jobs cookbook. A full copy of the stack trace is in a gist at: https://gist.github.com/ceseuron/31cefedbfc51a5f5fa245e44f1a3660d

**Comment by ABrehm264** [comment]
I ran into this problem as well, The problem is because the code is trying to pull the version from either the 'package_url' (using regex) or the 'package_version' attributes. You'll want to make sure that you have either the version number in the URL or the version specified when you're installing push-jobs.

**Comment by iennae** [comment]
Thanks @ABrehm264 for providing the update to documentation here on how to get this resolved. @ceseuron , hopefully this resolves your issue. If it doesn't please reopen with additional details.
